---
- name: Update yum cache
  yum:
    update_cache: yes

- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - wget
    - unzip
    - Xvfb

- name: Install Selenium
  pip:
    name: selenium
    executable: pip3

- name: Install Chrome browser
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    dest: /tmp/google-chrome-stable_current_x86_64.rpm

- name: Install Chrome browser
  yum:
    name: /tmp/google-chrome-stable_current_x86_64.rpm
    state: present

- name: Download Chrome WebDriver
  get_url:
    url: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
    dest: /tmp/chromedriver.zip
    mode: '0644'

- name: Unzip Chrome WebDriver
  unarchive:
    src: /tmp/chromedriver.zip
    dest: /usr/local/bin/
    copy: false

- name: Make Chrome WebDriver executable
  file:
    path: /usr/local/bin/chromedriver
    mode: '0755'
