---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python and pip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip

- name: Install Selenium
  pip:
    name: selenium
    executable: pip3

- name: Install Chrome browser
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - unzip
    - xvfb
    - google-chrome-stable
  when: ansible_os_family == 'Debian'

- name: Download Chrome WebDriver
  get_url:
    url: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
    dest: /tmp/chromedriver.zip
    mode: '0644'

- name: Unzip Chrome WebDriver
  unarchive:
    src: /tmp/chromedriver.zip
    dest: /usr/local/bin/
    copy: false

- name: Make Chrome WebDriver executable
  file:
    path: /usr/local/bin/chromedriver
    mode: '0755'
